# Generated by Django 4.1.2 on 2023-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerdb', '0002_boleta_producto_alter_cliente_rut_detalle_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.CharField(default=1, max_length=50, verbose_name='stock'),
            preserve_default=False,
        ),
    ]
